# $schema: ../schema.json
name: $asinh
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/asinh/'
type:
    - resolvesToDouble
    - resolvesToDecimal
encode: single
description: |
    Returns the inverse hyperbolic sine (hyperbolic arc sine) of a value in radians.
arguments:
    -
        name: expression
        type:
            - resolvesToNumber
        description: |
            $asinh takes any valid expression that resolves to a number.
            $asinh returns values in radians. Use $radiansToDegrees operator to convert the output value from radians to degrees.
            By default $asinh returns values as a double. $asinh can also return values as a 128-bit decimal as long as the expression resolves to a 128-bit decimal value.
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/asinh/#example'
        pipeline:
            -
                $addFields:
                    y-coordinate:
                        $radiansToDegrees:
                            $asinh: '$x-coordinate'
