# $schema: ../schema.json
name: $atan
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/atan/'
type:
    - resolvesToDouble
    - resolvesToDecimal
encode: single
description: |
    Returns the inverse tangent (arc tangent) of a value in radians.
arguments:
    -
        name: expression
        type:
            - resolvesToNumber
        description: |
            $atan takes any valid expression that resolves to a number.
            $atan returns values in radians. Use $radiansToDegrees operator to convert the output value from radians to degrees.
            By default $atan returns values as a double. $atan can also return values as a 128-bit decimal as long as the expression resolves to a 128-bit decimal value.
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/atan/#example'
        pipeline:
            -
                $addFields:
                    angle_a:
                        $radiansToDegrees:
                            $atan:
                                $divide:
                                    - '$side_b'
                                    - '$side_a'
