# $schema: ../schema.json
name: $atanh
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/atanh/'
type:
    - resolvesToDouble
    - resolvesToDecimal
encode: single
description: |
    Returns the inverse hyperbolic tangent (hyperbolic arc tangent) of a value in radians.
arguments:
    -
        name: expression
        type:
            - resolvesToNumber
        description: |
            $atanh takes any valid expression that resolves to a number between -1 and 1, e.g. -1 <= value <= 1.
            $atanh returns values in radians. Use $radiansToDegrees operator to convert the output value from radians to degrees.
            By default $atanh returns values as a double. $atanh can also return values as a 128-bit decimal as long as the expression resolves to a 128-bit decimal value.
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/atanh/#example'
        pipeline:
            -
                $addFields:
                    y-coordinate:
                        $radiansToDegrees:
                            $atanh: '$x-coordinate'
