# $schema: ../schema.json
name: $avg
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/avg/'
type:
    - resolvesToNumber
encode: single
description: |
    Returns an average of numerical values. Ignores non-numeric values.
    Changed in MongoDB 5.0: Available in the $setWindowFields stage.
arguments:
    -
        name: expression
        type:
            - resolvesToNumber
        variadic: array
tests:
    -
        name: 'Use in $project Stage'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/avg/#use-in--project-stage'
        pipeline:
            -
                $project:
                    quizAvg:
                        # $avg: '$quizzes'
                        $avg:
                            - '$quizzes'
                    labAvg:
                        # $avg: '$labs'
                        $avg:
                            - '$labs'
                    examAvg:
                        $avg:
                            - '$final'
                            - '$midterm'
