# $schema: ../schema.json
name: $bitOr
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/bitOr/'
type:
    - resolvesToInt
    - resolvesToLong
encode: single
description: |
    Returns the result of a bitwise or operation on an array of int or long values.
    New in MongoDB 6.3.
arguments:
    -
        name: expression
        type:
            - resolvesToInt
            - resolvesToLong
        variadic: array
tests:
    -
        name: 'Bitwise OR with Two Integers'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/bitOr/#bitwise-or-with-two-integers'
        pipeline:
            -
                $project:
                    result:
                        $bitOr:
                            - '$a'
                            - '$b'
    -
        name: 'Bitwise OR with a Long and Integer'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/bitOr/#bitwise-or-with-a-long-and-integer'
        pipeline:
            -
                $project:
                    result:
                        $bitOr:
                            - '$a'
                            - { "$numberLong": "63" }
