# $schema: ../schema.json
name: $cond
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/'
type:
    - resolvesToAny
encode: object
description: |
    A ternary operator that evaluates one expression, and depending on the result, returns the value of one of the other two expressions. Accepts either three expressions in an ordered list or three named parameters.
arguments:
    -
        name: if
        type:
            - resolvesToBool
    -
        name: then
        type:
            - expression
    -
        name: else
        type:
            - expression
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/#example'
        pipeline:
            -
                $project:
                    item: 1
                    discount:
                        $cond:
                            if:
                                $gte:
                                    - '$qty'
                                    - 250
                            then: 30
                            else: 20
