# $schema: ../schema.json
name: $degreesToRadians
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/degreesToRadians/'
type:
    - resolvesToDouble
    - resolvesToDecimal
encode: single
description: |
    Converts a value from degrees to radians.
arguments:
    -
        name: expression
        type:
            - resolvesToNumber
        description: |
            $degreesToRadians takes any valid expression that resolves to a number.
            By default $degreesToRadians returns values as a double. $degreesToRadians can also return values as a 128-bit decimal as long as the <expression> resolves to a 128-bit decimal value.
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/degreesToRadians/#example'
        pipeline:
            -
                $addFields:
                    angle_a_rad:
                        $degreesToRadians: '$angle_a'
                    angle_b_rad:
                        $degreesToRadians: '$angle_b'
                    angle_c_rad:
                        $degreesToRadians: '$angle_c'
