# $schema: ../schema.json
name: $eq
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/'
type:
    - resolvesToBool
encode: array
description: |
    Returns true if the values are equivalent.
arguments:
    -
        name: expression1
        type:
            - expression
    -
        name: expression2
        type:
            - expression
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/#example'
        pipeline:
            -
                $project:
                    item: 1
                    qty: 1
                    qtyEq250:
                        $eq:
                            - '$qty'
                            - 250
                    _id: 0
