# $schema: ../schema.json
name: $function
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/function/'
type:
    - resolvesToAny
encode: object
description: |
    Defines a custom function.
    New in MongoDB 4.4.
arguments:
    -
        name: body
        type:
            - javascript
        description: |
            The function definition. You can specify the function definition as either BSON\JavaScript or string.
            function(arg1, arg2, ...) { ... }
    -
        name: args
        type:
            - array
        description: |
            Arguments passed to the function body. If the body function does not take an argument, you can specify an empty array [ ].
    -
        name: lang
        type:
            - string
        default: js
