# $schema: ../schema.json
name: $gt
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/gt/'
type:
    - resolvesToBool
encode: array
description: |
    Returns true if the first value is greater than the second.
arguments:
    -
        name: expression1
        type:
            - expression
    -
        name: expression2
        type:
            - expression
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/gt/#example'
        pipeline:
            -
                $project:
                    item: 1
                    qty: 1
                    qtyGt250:
                        $gt:
                            - '$qty'
                            - 250
                    _id: 0
