# $schema: ../schema.json
name: $in
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/in/'
type:
    - resolvesToBool
encode: array
description: |
    Returns a boolean indicating whether a specified value is in an array.
arguments:
    -
        name: expression
        type:
            - expression
        description: |
            Any valid expression expression.
    -
        name: array
        type:
            - resolvesToArray
        description: |
            Any valid expression that resolves to an array.
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/in/#example'
        pipeline:
            -
                $project:
                    store location: '$location'
                    has bananas:
                        $in:
                            - 'bananas'
                            - '$in_stock'
