# $schema: ../schema.json
name: $isNumber
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/isNumber/'
type:
    - resolvesToBool
encode: single
description: |
    Returns boolean true if the specified expression resolves to an integer, decimal, double, or long.
    Returns boolean false if the expression resolves to any other BSON type, null, or a missing field.
    New in MongoDB 4.4.
arguments:
    -
        name: expression
        type:
            - expression
tests:
    -
        name: 'Use $isNumber to Check if a Field is Numeric'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/isNumber/#use--isnumber-to-check-if-a-field-is-numeric'
        pipeline:
            -
                $addFields:
                    isNumber:
                        $isNumber: '$reading'
                    hasType:
                        $type: '$reading'
    -
        name: 'Conditionally Modify Fields using $isNumber'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/isNumber/#conditionally-modify-fields-using--isnumber'
        pipeline:
            -
                $addFields:
                    points:
                        $cond:
                            if:
                                $isNumber: '$grade'
                            then: '$grade'
                            else:
                                $switch:
                                    branches:
                                        -
                                            case:
                                                $eq:
                                                    - '$grade'
                                                    - 'A'
                                            then: 4
                                        -
                                            case:
                                                $eq:
                                                    - '$grade'
                                                    - 'B'
                                            then: 3
                                        -
                                            case:
                                                $eq:
                                                    - '$grade'
                                                    - 'C'
                                            then: 2
                                        -
                                            case:
                                                $eq:
                                                    - '$grade'
                                                    - 'D'
                                            then: 1
                                        -
                                            case:
                                                $eq:
                                                    - '$grade'
                                                    - 'F'
                                            then: 0
            -
                $group:
                    _id: '$student_id'
                    GPA:
                        $avg: '$points'
