# $schema: ../schema.json
name: $isoWeekYear
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/isoWeekYear/'
type:
    - resolvesToInt
encode: object
description: |
    Returns the year number in ISO 8601 format. The year starts with the Monday of week 1 (ISO 8601) and ends with the Sunday of the last week (ISO 8601).
arguments:
    -
        name: date
        type:
            - resolvesToDate
            - resolvesToTimestamp
            - resolvesToObjectId
        description: |
            The date to which the operator is applied. date must be a valid expression that resolves to a Date, a Timestamp, or an ObjectID.
    -
        name: timezone
        type:
            - resolvesToString
        optional: true
        description: |
            The timezone of the operation result. timezone must be a valid expression that resolves to a string formatted as either an Olson Timezone Identifier or a UTC Offset. If no timezone is provided, the result is displayed in UTC.
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/isoWeekYear/#example'
        pipeline:
            -
                $project:
                    yearNumber:
                        # Example uses the short form, the builder always generates the verbose form
                        # $isoWeekYear: '$date'
                        $isoWeekYear:
                            date: '$date'
