# $schema: ../schema.json
name: $literal
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/literal/'
type:
    - resolvesToAny
encode: single
description: |
    Return a value without parsing. Use for values that the aggregation pipeline may interpret as an expression. For example, use a $literal expression to a string that starts with a dollar sign ($) to avoid parsing as a field path.
arguments:
    -
        name: value
        type:
            - any
        description: |
            If the value is an expression, $literal does not evaluate the expression but instead returns the unparsed expression.
