# $schema: ../schema.json
name: $lte
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/lte/'
type:
    - resolvesToBool
encode: array
description: |
    Returns true if the first value is less than or equal to the second.
arguments:
    -
        name: expression1
        type:
            - expression
    -
        name: expression2
        type:
            - expression
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/lte/#example'
        pipeline:
            -
                $project:
                    item: 1
                    qty: 1
                    qtyLte250:
                        $lte:
                            - '$qty'
                            - 250
                    _id: 0
