# $schema: ../schema.json
name: $ltrim
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/ltrim/'
type:
    - resolvesToString
encode: object
description: |
    Removes whitespace or the specified characters from the beginning of a string.
    New in MongoDB 4.0.
arguments:
    -
        name: input
        type:
            - resolvesToString
        description: |
            The string to trim. The argument can be any valid expression that resolves to a string.
    -
        name: chars
        type:
            - resolvesToString
        optional: true
        description: |
            The character(s) to trim from the beginning of the input.
            The argument can be any valid expression that resolves to a string. The $ltrim operator breaks down the string into individual UTF code point to trim from input.
            If unspecified, $ltrim removes whitespace characters, including the null character.
