# $schema: ../schema.json
name: $max
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/max/'
type:
    - resolvesToAny
encode: single
description: |
    Returns the maximum value that results from applying an expression to each document.
    Changed in version 5.0: Available in the $setWindowFields stage.
arguments:
    -
        name: expression
        type:
            - expression
        variadic: array
