# $schema: ../schema.json
name: $meta
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/meta/'
type:
    - resolvesToAny
encode: single
description: |
    Access available per-document metadata related to the aggregation operation.
arguments:
    -
        name: keyword
        type:
            - string
