# $schema: ../schema.json
name: $min
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/min/'
type:
    - resolvesToAny
encode: single
description: |
    Returns the minimum value that results from applying an expression to each document.
    Changed in MongoDB 5.0: Available in the $setWindowFields stage.
arguments:
    -
        name: expression
        type:
            - expression
        variadic: array
tests:
    -
        name: 'Use in $project Stage'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/min/#use-in--project-stage'
        pipeline:
            -
                $project:
                    quizMin:
                        # Example uses the short form, the builder always generates the verbose form
                        # $min: '$quizzes'
                        $min:
                            - '$quizzes'
                    labMin:
                        # $min: '$labs'
                        $min:
                            - '$labs'
                    examMin:
                        $min:
                            - '$final'
                            - '$midterm'
