# $schema: ../schema.json
name: $setField
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/setField/'
type:
    - resolvesToObject
encode: object
description: |
    Adds, updates, or removes a specified field in a document. You can use $setField to add, update, or remove fields with names that contain periods (.) or start with dollar signs ($).
    New in version 5.0.
arguments:
    -
        name: field
        type:
            - resolvesToString
        description: |
            Field in the input object that you want to add, update, or remove. field can be any valid expression that resolves to a string constant.
    -
        name: input
        type:
            - resolvesToObject
        description: |
            Document that contains the field that you want to add or update. input must resolve to an object, missing, null, or undefined.
    -
        name: value
        type:
            - expression
        description: |
            The value that you want to assign to field. value can be any valid expression.
            Set to $$REMOVE to remove field from the input document.
