# $schema: ../schema.json
name: $setIntersection
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/setIntersection/'
type:
    - resolvesToArray
encode: single
description: |
    Returns a set with elements that appear in all of the input sets. Accepts any number of argument expressions.
arguments:
    -
        name: expression
        type:
            - resolvesToArray
        variadic: array
