# $schema: ../schema.json
name: $sin
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/sin/'
type:
    - resolvesToDouble
    - resolvesToDecimal
encode: single
description: |
    Returns the sine of a value that is measured in radians.
arguments:
    -
        name: expression
        type:
            - resolvesToNumber
        description: |
            $sin takes any valid expression that resolves to a number. If the expression returns a value in degrees, use the $degreesToRadians operator to convert the result to radians.
            By default $sin returns values as a double. $sin can also return values as a 128-bit decimal as long as the expression resolves to a 128-bit decimal value.
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/sin/#example'
        pipeline:
            -
                $addFields:
                    side_b:
                        $multiply:
                            -
                                $sin:
                                    $degreesToRadians: '$angle_a'
                            - '$hypotenuse'
