# $schema: ../schema.json
name: $split
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/split/'
type:
    - resolvesToArray # of string
encode: array
description: |
    Splits a string into substrings based on a delimiter. Returns an array of substrings. If the delimiter is not found within the string, returns an array containing the original string.
arguments:
    -
        name: string
        type:
            - resolvesToString
        description: |
            The string to be split. string expression can be any valid expression as long as it resolves to a string.
    -
        name: delimiter
        type:
            - resolvesToString
        description: |
            The delimiter to use when splitting the string expression. delimiter can be any valid expression as long as it resolves to a string.
