# $schema: ../schema.json
name: $sqrt
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/sqrt/'
type:
    - resolvesToDouble
encode: single
description: |
    Calculates the square root.
arguments:
    -
        name: number
        type:
            - resolvesToNumber
        description: |
            The argument can be any valid expression as long as it resolves to a non-negative number.
