# $schema: ../schema.json
name: $tan
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/tan/'
type:
    - resolvesToDouble
    - resolvesToDecimal
encode: single
description: |
    Returns the tangent of a value that is measured in radians.
arguments:
    -
        name: expression
        type:
            - resolvesToNumber
        description: |
            $tan takes any valid expression that resolves to a number. If the expression returns a value in degrees, use the $degreesToRadians operator to convert the result to radians.
            By default $tan returns values as a double. $tan can also return values as a 128-bit decimal as long as the expression resolves to a 128-bit decimal value.
