# $schema: ../schema.json
name: $toDouble
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/toDouble/'
type:
    - resolvesToDouble
encode: single
description: |
    Converts value to a double.
    New in MongoDB 4.0.
arguments:
    -
        name: expression
        type:
            - expression
