# $schema: ../schema.json
name: $toInt
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/toInt/'
type:
    - resolvesToInt
encode: single
description: |
    Converts value to an integer.
    New in version 4.0.
arguments:
    -
        name: expression
        type:
            - expression
