# $schema: ../schema.json
name: $tsIncrement
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/tsIncrement/'
type:
    - resolvesToLong
encode: single
description: |
    Returns the incrementing ordinal from a timestamp as a long.
    New in MongoDB 5.1.
arguments:
    -
        name: expression
        type:
            - resolvesToTimestamp
