# $schema: ../schema.json
name: $covariancePop
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/covariancePop/'
type:
    - window
encode: array
description: |
    Returns the population covariance of two numeric expressions.
    New in MongoDB 5.0.
arguments:
    -
        name: expression1
        type:
            - resolvesToNumber
    -
        name: expression2
        type:
            - resolvesToNumber
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/covariancePop/#example'
        pipeline:
            -
                $setWindowFields:
                    partitionBy: '$state'
                    sortBy:
                        orderDate: 1
                    output:
                        covariancePopForState:
                            $covariancePop:
                                -
                                    # $year: '$orderDate'
                                    $year:
                                        date: '$orderDate'
                                - '$quantity'
                            window:
                                documents:
                                    - 'unbounded'
                                    - 'current'
