# $schema: ../schema.json
name: $derivative
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/derivative/'
type:
    - window
encode: object
description: |
    Returns the average rate of change within the specified window.
    New in MongoDB 5.0.
arguments:
    -
        name: input
        type:
            - resolvesToNumber
            - resolvesToDate
    -
        name: unit
        type:
            - string
        optional: true
        description: |
            A string that specifies the time unit. Use one of these strings: "week", "day","hour", "minute", "second", "millisecond".
            If the sortBy field is not a date, you must omit a unit. If you specify a unit, you must specify a date in the sortBy field.
