# $schema: ../schema.json
name: $max
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/max/'
type:
    - accumulator
    - window
encode: single
description: |
    Returns the maximum value that results from applying an expression to each document.
    Changed in MongoDB 5.0: Available in the $setWindowFields stage.
arguments:
    -
        name: expression
        type:
            - expression
tests:
    -
        name: 'Use in $group Stage'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/max/#use-in--group-stage'
        pipeline:
            -
                $group:
                    _id: '$item'
                    maxTotalAmount:
                        $max:
                            $multiply:
                                - '$price'
                                - '$quantity'
                    maxQuantity:
                        $max: '$quantity'
    -
        name: 'Use in $setWindowFields Stage'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/max/#use-in--setwindowfields-stage'
        pipeline:
            -
                $setWindowFields:
                    partitionBy: '$state'
                    sortBy:
                        orderDate: 1
                    output:
                        maximumQuantityForState:
                            $max: '$quantity'
                            window:
                                documents:
                                    - 'unbounded'
                                    - 'current'
