# $schema: ../schema.json
name: $min
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/min/'
type:
    - accumulator
    - window
encode: single
description: |
    Returns the minimum value that results from applying an expression to each document.
    Changed in MongoDB 5.0: Available in the $setWindowFields stage.
arguments:
    -
        name: expression
        type:
            - expression
