# $schema: ../schema.json
name: $percentile
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/percentile/'
type:
    - accumulator
    - window
encode: object
description: |
    Returns an array of scalar values that correspond to specified percentile values.
    New in MongoDB 7.0.

    This operator is available as an accumulator in these stages:
    $group

    $setWindowFields

    It is also available as an aggregation expression.
arguments:
    -
        name: input
        type:
            - resolvesToNumber
        description: |
            $percentile calculates the percentile values of this data. input must be a field name or an expression that evaluates to a numeric type. If the expression cannot be converted to a numeric type, the $percentile calculation ignores it.
    -
        name: p
        type:
            - resolvesToArray # of resolvesToNumber
        description: |
            $percentile calculates a percentile value for each element in p. The elements represent percentages and must evaluate to numeric values in the range 0.0 to 1.0, inclusive.
            $percentile returns results in the same order as the elements in p.
    -
        name: method
        type:
            - string # AccumulatorPercentile
        description: |
            The method that mongod uses to calculate the percentile value. The method must be 'approximate'.
tests:
    -
        name: 'Calculate a Single Value as an Accumulator'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/percentile/#calculate-a-single-value-as-an-accumulator'
        pipeline:
            -
                $group:
                    _id: ~
                    test01_percentiles:
                        $percentile:
                            input: '$test01'
                            p:
                                - 0.95
                            method: 'approximate'
    -
        name: 'Calculate Multiple Values as an Accumulator'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/percentile/#calculate-multiple-values-as-an-accumulator'
        pipeline:
            -
                $group:
                    _id: ~
                    test01_percentiles:
                        $percentile:
                            input: '$test01'
                            p: [0.5, 0.75, 0.9, 0.95]
                            method: 'approximate'
                    test02_percentiles:
                        $percentile:
                            input: '$test02'
                            p: [0.5, 0.75, 0.9, 0.95]
                            method: 'approximate'
                    test03_percentiles:
                        $percentile:
                            input: '$test03'
                            p: [0.5, 0.75, 0.9, 0.95]
                            method: 'approximate'
                    test03_percent_alt:
                        $percentile:
                            input: '$test03'
                            p: [0.9, 0.5, 0.75, 0.95]
                            method: 'approximate'
    -
        name: 'Use $percentile in a $setWindowField Stage'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/percentile/#use-operatorname-in-a--setwindowfield-stage'
        pipeline:
            -
                $setWindowFields:
                    sortBy:
                        test01: 1
                    output:
                        test01_95percentile:
                            $percentile:
                                input: '$test01'
                                p:
                                    - 0.95
                                method: 'approximate'
                            window:
                                range:
                                    - -3
                                    - 3
            -
                $project:
                    _id: 0
                    studentId: 1
                    test01_95percentile: 1
