# $schema: ../schema.json
name: $rank
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/rank/'
type:
    - window
encode: object
description: |
    Returns the document position (known as the rank) relative to other documents in the $setWindowFields stage partition.
    New in MongoDB 5.0.
tests:
    -
        name: 'Rank Partitions by an Integer Field'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/rank/#rank-partitions-by-an-integer-field'
        pipeline:
            -
                $setWindowFields:
                    partitionBy: '$state'
                    sortBy:
                        quantity: -1
                    output:
                        rankQuantityForState:
                            $rank: {}
    -
        name: 'Rank Partitions by a Date Field'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/rank/#rank-partitions-by-a-date-field'
        pipeline:
            -
                $setWindowFields:
                    partitionBy: '$state'
                    sortBy:
                        orderDate: 1
                    output:
                        rankOrderDateForState:
                            $rank: {}
