# $schema: ../schema.json
name: $stdDevPop
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/stdDevPop/'
type:
    - accumulator
    - window
encode: single
description: |
    Calculates the population standard deviation of the input values. Use if the values encompass the entire population of data you want to represent and do not wish to generalize about a larger population. $stdDevPop ignores non-numeric values.
    If the values represent only a sample of a population of data from which to generalize about the population, use $stdDevSamp instead.
    Changed in MongoDB 5.0: Available in the $setWindowFields stage.
arguments:
    -
        name: expression
        type:
            - resolvesToNumber
tests:
    -
        name: 'Use in $group Stage'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/stdDevPop/#use-in--group-stage'
        pipeline:
            -
                $group:
                    _id: '$quiz'
                    stdDev:
                        $stdDevPop: '$score'
    -
        name: 'Use in $setWindowFields Stage'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/stdDevPop/#use-in--setwindowfields-stage'
        pipeline:
            -
                $setWindowFields:
                    partitionBy: '$state'
                    sortBy:
                        orderDate: 1
                    output:
                        stdDevPopQuantityForState:
                            $stdDevPop: '$quantity'
                            window:
                                documents: ['unbounded', 'current']
