# $schema: ../schema.json
name: $top
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/top/'
type:
    - accumulator
encode: object
description: |
    Returns the top element within a group according to the specified sort order.
    New in MongoDB 5.2.

    Available in the $group and $setWindowFields stages.
arguments:
    -
        name: sortBy
        type:
            - object # SortSpec
        description: |
            Specifies the order of results, with syntax similar to $sort.
    -
        name: output
        type:
            - expression
        description: |
            Represents the output for each element in the group and can be any expression.
