# $schema: ../schema.json
name: $elemMatch
link: 'https://www.mongodb.com/docs/manual/reference/operator/projection/elemMatch/'
type:
    - projection
encode: single
description: |
    Projects the first element in an array that matches the specified $elemMatch condition.
arguments:
    -
        name: query
        type:
            - query
tests:
    -
        name: 'Zipcode Search'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/projection/elemMatch/#zipcode-search'
        pipeline:
            -
                $match:
                    zipcode: '63109'
            -
                $project:
                    students:
                        $elemMatch:
                            school: 102
    -
        name: 'with Multiple Fields'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/projection/elemMatch/#with-multiple-fields'
        pipeline:
            -
                $match:
                    zipcode: '63109'
            -
                $project:
                    students:
                        $elemMatch:
                            school: 102
                            age:
                                $gt: 10
