# $schema: ../schema.json
name: $slice
link: 'https://www.mongodb.com/docs/manual/reference/operator/projection/slice/'
type:
    - projection
encode: array
description: |
    Limits the number of elements projected from an array. Supports skip and limit slices.
arguments:
    -
        name: limit
        type:
            - int
    -
        name: skip
        type:
            - int
        optional: true
tests:
    -
        name: 'Return an Array with Its First 3 Elements'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/projection/slice/#return-an-array-with-its-first-3-elements'
        pipeline:
            -
                $project:
                    comments:
                        # Example uses the short form, the builder always generated the verbose form
                        # $slice: 3
                        $slice: [3]
    -
        name: 'Return an Array with Its Last 3 Elements'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/projection/slice/#return-an-array-with-its-last-3-elements'
        pipeline:
            -
                $project:
                    comments:
                        # Example uses the short form, the builder always generated the verbose form
                        # $slice: -3
                        $slice: [-3]
    -
        name: 'Return an Array with 3 Elements After Skipping the First Element'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/projection/slice/#return-an-array-with-3-elements-after-skipping-the-first-element'
        pipeline:
            -
                $project:
                    comments:
                        $slice: [1, 3]
    -
        name: 'Return an Array with 3 Elements After Skipping the Last Element'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/projection/slice/#return-an-array-with-3-elements-after-skipping-the-last-element'
        pipeline:
            -
                $project:
                    comments:
                        $slice: [-1, 3]
