# $schema: ../schema.json
name: $addFields
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/addFields/'
type:
    - stage
encode: single
description: |
    Adds new fields to documents. Outputs documents that contain all existing fields from the input documents and newly added fields.
arguments:
    -
        name: expression
        type:
            - expression
        variadic: object
        description: |
            Specify the name of each field to add and set its value to an aggregation expression or an empty object.
tests:
    -
        name: 'Using Two $addFields Stages'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/addFields/#using-two--addfields-stages'
        pipeline:
            -
                $addFields:
                    totalHomework:
                        $sum: '$homework'
                    totalQuiz:
                        $sum: '$quiz'
            -
                $addFields:
                    totalScore:
                        $add:
                            - '$totalHomework'
                            - '$totalQuiz'
                            - '$extraCredit'
    -
        name: 'Adding Fields to an Embedded Document'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/addFields/#adding-fields-to-an-embedded-document'
        pipeline:
            -
                $addFields:
                    specs.fuel_type: 'unleaded'
