# $schema: ../schema.json
name: $bucketAuto
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/bucketAuto/'
type:
    - stage
encode: object
description: |
    Categorizes incoming documents into a specific number of groups, called buckets, based on a specified expression. Bucket boundaries are automatically determined in an attempt to evenly distribute the documents into the specified number of buckets.
arguments:
    -
        name: groupBy
        type:
            - expression
        description: |
            An expression to group documents by. To specify a field path, prefix the field name with a dollar sign $ and enclose it in quotes.
    -
        name: buckets
        type:
            - int
        description: |
            A positive 32-bit integer that specifies the number of buckets into which input documents are grouped.
    -
        name: output
        type:
            - object # of Accumulator
        optional: true
        description: |
            A document that specifies the fields to include in the output documents in addition to the _id field. To specify the field to include, you must use accumulator expressions.
            The default count field is not included in the output document when output is specified. Explicitly specify the count expression as part of the output document to include it.
    -
        name: granularity
        type:
            - object # Granularity
        optional: true
        description: |
            A string that specifies the preferred number series to use to ensure that the calculated boundary edges end on preferred round numbers or their powers of 10.
            Available only if the all groupBy values are numeric and none of them are NaN.
tests:
    -
        name: 'Single Facet Aggregation'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/bucketAuto/#single-facet-aggregation'
        pipeline:
            -
                $bucketAuto:
                    groupBy: '$price'
                    buckets: 4
