# $schema: ../schema.json
name: $documents
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/documents/'
type:
    - stage
encode: single
description: |
    Returns literal documents from input values.
arguments:
    -
        name: documents
        type:
            - resolvesToArray # of object
        description: |
            $documents accepts any valid expression that resolves to an array of objects. This includes:
            - system variables, such as $$NOW or $$SEARCH_META
            - $let expressions
            - variables in scope from $lookup expressions
            Expressions that do not resolve to a current document, like $myField or $$ROOT, will result in an error.
tests:
    -
        name: 'Test a Pipeline Stage'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/documents/#test-a-pipeline-stage'
        pipeline:
            -
                $documents:
                    - { x: 10 }
                    - { x: 2 }
                    - { x: 5 }
            -
                $bucketAuto:
                    groupBy: '$x'
                    buckets: 4
    -
        name: 'Use a $documents Stage in a $lookup Stage'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/documents/#use-a--documents-stage-in-a--lookup-stage'
        pipeline:
            -
                $match: {}
            -
                $lookup:
                    localField: 'zip'
                    foreignField: 'zip_id'
                    as: 'city_state'
                    pipeline:
                        -
                            $documents:
                                -
                                    zip_id: 94301
                                    name: 'Palo Alto, CA'
                                -
                                    zip_id: 10019
                                    name: 'New York, NY'
