# $schema: ../schema.json
name: $facet
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/facet/'
type:
    - stage
encode: single
description: |
    Processes multiple aggregation pipelines within a single stage on the same set of input documents. Enables the creation of multi-faceted aggregations capable of characterizing data across multiple dimensions, or facets, in a single stage.
arguments:
    -
        name: facet
        type:
            - pipeline
        variadic: object
