# $schema: ../schema.json
name: $facet
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/facet/'
type:
    - stage
encode: single
description: |
    Processes multiple aggregation pipelines within a single stage on the same set of input documents. Enables the creation of multi-faceted aggregations capable of characterizing data across multiple dimensions, or facets, in a single stage.
arguments:
    -
        name: facet
        type:
            - pipeline
        variadic: object
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/facet/#example'
        pipeline:
            -
                $facet:
                    categorizedByTags:
                        -
                            # The builder uses the verbose form of the $unwind operator
                            # $unwind: '$tags'
                            $unwind:
                                path: '$tags'
                        -
                            $sortByCount: '$tags'
                    categorizedByPrice:
                        -
                            $match:
                                price:
                                    # The example uses an int, but the builder requires a bool
                                    # $exists: 1
                                    $exists: true
                        -
                            $bucket:
                                groupBy: '$price'
                                boundaries: [0, 150, 200, 300, 400]
                                default: 'Other'
                                output:
                                    count:
                                        $sum: 1
                                    titles:
                                        $push: '$title'
                    categorizedByYears(Auto):
                        -
                            $bucketAuto:
                                groupBy: '$year'
                                buckets: 4
