# $schema: ../schema.json
name: $geoNear
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/geoNear/'
type:
    - stage
encode: object
description: |
    Returns an ordered stream of documents based on the proximity to a geospatial point. Incorporates the functionality of $match, $sort, and $limit for geospatial data. The output documents include an additional distance field and can include a location identifier field.
arguments:
    -
        name: distanceField
        type:
            - string
        description: |
            The output field that contains the calculated distance. To specify a field within an embedded document, use dot notation.
    -
        name: distanceMultiplier
        type:
            - number
        optional: true
        description: |
            The factor to multiply all distances returned by the query. For example, use the distanceMultiplier to convert radians, as returned by a spherical query, to kilometers by multiplying by the radius of the Earth.
    -
        name: includeLocs
        type:
            - string
        optional: true
        description: |
            This specifies the output field that identifies the location used to calculate the distance. This option is useful when a location field contains multiple locations. To specify a field within an embedded document, use dot notation.
    -
        name: key
        type:
            - string
        optional: true
        description: |
            Specify the geospatial indexed field to use when calculating the distance.
    -
        name: maxDistance
        type:
            - number
        optional: true
        description: |
            The maximum distance from the center point that the documents can be. MongoDB limits the results to those documents that fall within the specified distance from the center point.
            Specify the distance in meters if the specified point is GeoJSON and in radians if the specified point is legacy coordinate pairs.
    -
        name: minDistance
        type:
            - number
        optional: true
        description: |
            The minimum distance from the center point that the documents can be. MongoDB limits the results to those documents that fall outside the specified distance from the center point.
            Specify the distance in meters for GeoJSON data and in radians for legacy coordinate pairs.
    -
        name: near
        type:
            - object # GeoPoint
            - resolvesToObject
        description: |
            The point for which to find the closest documents.
    -
        name: query
        type:
            - query
        optional: true
        description: |
            Limits the results to the documents that match the query. The query syntax is the usual MongoDB read operation query syntax.
            You cannot specify a $near predicate in the query field of the $geoNear stage.
    -
        name: spherical
        type:
            - bool
        optional: true
        description: |
            Determines how MongoDB calculates the distance between two points:
            - When true, MongoDB uses $nearSphere semantics and calculates distances using spherical geometry.
            - When false, MongoDB uses $near semantics: spherical geometry for 2dsphere indexes and planar geometry for 2d indexes.
            Default: false.
tests:
    -
        name: 'Maximum Distance'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/geoNear/#maximum-distance'
        pipeline:
            -
                $geoNear:
                    near:
                        type: 'Point'
                        coordinates:
                            - -73.99279
                            - 40.719296
                    distanceField: 'dist.calculated'
                    maxDistance: 2
                    query:
                        category: 'Parks'
                    includeLocs: 'dist.location'
                    spherical: true
    -
        name: 'Minimum Distance'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/geoNear/#minimum-distance'
        pipeline:
            -
                $geoNear:
                    near:
                        type: 'Point'
                        coordinates:
                            - -73.99279
                            - 40.719296
                    distanceField: 'dist.calculated'
                    minDistance: 2
                    query:
                        category: 'Parks'
                    includeLocs: 'dist.location'
                    spherical: true
    -
        name: 'with the let option'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/geoNear/#-geonear-with-the-let-option'
        pipeline:
            -
                $geoNear:
                    near: '$$pt'
                    distanceField: 'distance'
                    maxDistance: 2
                    query:
                        category: 'Parks'
                    includeLocs: 'dist.location'
                    spherical: true
    -
        name: 'with Bound let Option'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/geoNear/#-geonear-with-bound-let-option'
        pipeline:
            -
                $lookup:
                    from: 'places'
                    let:
                        pt: '$location'
                    pipeline:
                        -
                            $geoNear:
                                near: '$$pt'
                                distanceField: 'distance'
                    as: 'joinedField'
            -
                $match:
                    name: 'Sara D. Roosevelt Park'
    -
        name: 'Specify Which Geospatial Index to Use'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/geoNear/#specify-which-geospatial-index-to-use'
        pipeline:
            -
                $geoNear:
                    near:
                        type: 'Point'
                        coordinates:
                            - -73.98142
                            - 40.71782
                    key: 'location'
                    distanceField: 'dist.calculated'
                    query:
                        category: 'Parks'
            -
                $limit: 5
