# $schema: ../schema.json
name: $listSampledQueries
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/listSampledQueries/'
type:
    - stage
encode: object
description: |
    Lists sampled queries for all collections or a specific collection.
arguments:
    -
        name: namespace
        type:
            - string
        optional: true
tests:
    -
        name: 'List Sampled Queries for All Collections'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/listSampledQueries/#list-sampled-queries-for-all-collections'
        pipeline:
            -
                $listSampledQueries: {}

    -
        name: 'List Sampled Queries for A Specific Collection'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/listSampledQueries/#list-sampled-queries-for-a-specific-collection'
        pipeline:
            -
                $listSampledQueries:
                    namespace: 'social.post'
