# $schema: ../schema.json
name: $listSessions
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/listSessions/'
type:
    - stage
encode: object
description: |
    Lists all sessions that have been active long enough to propagate to the system.sessions collection.
arguments:
    -
        name: users
        type:
            - array
        optional: true
        description: |
            Returns all sessions for the specified users. If running with access control, the authenticated user must have privileges with listSessions action on the cluster to list sessions for other users.
    -
        name: allUsers
        type:
            - bool
        optional: true
        description: |
            Returns all sessions for all users. If running with access control, the authenticated user must have privileges with listSessions action on the cluster.
tests:
    -
        name: 'List All Sessions'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/listSessions/#list-all-sessions'
        pipeline:
            -
                $listSessions:
                    allUsers: true
    -
        name: 'List All Sessions for the Specified Users'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/listSessions/#list-all-sessions-for-the-specified-users'
        pipeline:
            -
                $listSessions:
                    users:
                        -
                            user: 'myAppReader'
                            db: 'test'
    -
        name: 'List All Sessions for the Current User'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/listSessions/#list-all-sessions-for-the-current-user'
        pipeline:
            -
                $listSessions: {}

