# $schema: ../schema.json
name: $listSearchIndexes
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/listSearchIndexes/'
type:
    - stage
encode: object
description: |
    Returns information about existing Atlas Search indexes on a specified collection.
arguments:
    -
        name: id
        type:
            - string
        optional: true
        description: |
            The id of the index to return information about.
    -
        name: name
        type:
            - string
        optional: true
        description: |
            The name of the index to return information about.
tests:
    -
        name: 'Return All Search Indexes'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/listSearchIndexes/#return-all-search-indexes'
        pipeline:
            -
                $listSearchIndexes: {}
    -
        name: 'Return a Single Search Index by Name'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/listSearchIndexes/#return-a-single-search-index-by-name'
        pipeline:
            -
                $listSearchIndexes:
                    name: 'synonym-mappings'
    -
        name: 'Return a Single Search Index by id'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/listSearchIndexes/#return-a-single-search-index-by-id'
        pipeline:
            -
                $listSearchIndexes:
                    id: '6524096020da840844a4c4a7'
