# $schema: ../schema.json
name: $out
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/out/'
type:
    - stage
encode: single
description: |
    Writes the resulting documents of the aggregation pipeline to a collection. To use the $out stage, it must be the last stage in the pipeline.
arguments:
    -   name: coll
        type:
            - string
            - object # OutCollection
        description: |
            Target database name to write documents from $out to.
tests:
    -
        name: 'Output to Same Database'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/out/#output-to-same-database'
        pipeline:
            -
                $group:
                    _id: '$author'
                    books:
                        $push: '$title'
            -
                $out: 'authors'
    -
        name: 'Output to a Different Database'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/out/#output-to-a-different-database'
        pipeline:
            -
                $group:
                    _id: '$author'
                    books:
                        $push: '$title'
            -
                $out:
                    db: 'reporting'
                    coll: 'authors'
