# $schema: ../schema.json
name: $search
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/search/'
type:
    - stage
encode: single
description: |
    Performs a full-text search of the field or fields in an Atlas collection.
    NOTE: $search is only available for MongoDB Atlas clusters, and is not available for self-managed deployments.
arguments:
    -
        name: search
        type:
            - object
