# $schema: ../schema.json
name: $searchMeta
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/searchMeta/'
type:
    - stage
encode: single
description: |
    Returns different types of metadata result documents for the Atlas Search query against an Atlas collection.
    NOTE: $searchMeta is only available for MongoDB Atlas clusters running MongoDB v4.4.9 or higher, and is not available for self-managed deployments.
arguments:
    -
        name: meta
        type:
            - object

tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/atlas/atlas-search/query-syntax/#example'
        pipeline:
            -
                $searchMeta:
                    range:
                        path: 'year'
                        gte: 1998
                        lt: 1999
                    count:
                        type: 'total'
