# $schema: ../schema.json
name: $setWindowFields
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/setWindowFields/'
type:
    - stage
encode: object
description: |
    Groups documents into windows and applies one or more operators to the documents in each window.
    New in MongoDB 5.0.
arguments:
    -
        name: sortBy
        type:
            - object # SortSpec
        description: |
            Specifies the field(s) to sort the documents by in the partition. Uses the same syntax as the $sort stage. Default is no sorting.
    -
        name: output
        type:
            - object
        description: |
            Specifies the field(s) to append to the documents in the output returned by the $setWindowFields stage. Each field is set to the result returned by the window operator.
            A field can contain dots to specify embedded document fields and array fields. The semantics for the embedded document dotted notation in the $setWindowFields stage are the same as the $addFields and $set stages.
    -
        name: partitionBy
        type:
            - expression
        description: |
            Specifies an expression to group the documents. In the $setWindowFields stage, the group of documents is known as a partition. Default is one partition for the entire collection.
        optional: true
tests:
    -
        name: 'Use Documents Window to Obtain Cumulative Quantity for Each State'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/setWindowFields/#use-documents-window-to-obtain-cumulative-quantity-for-each-state'
        pipeline:
            -
                $setWindowFields:
                    partitionBy: '$state'
                    sortBy:
                        orderDate: 1
                    output:
                        cumulativeQuantityForState:
                            $sum: '$quantity'
                            window:
                                documents: ['unbounded', 'current']
    -
        name: 'Use Documents Window to Obtain Cumulative Quantity for Each Year'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/setWindowFields/#use-documents-window-to-obtain-cumulative-quantity-for-each-year'
        pipeline:
            -
                $setWindowFields:
                    partitionBy:
                        # $year: '$orderDate'
                        $year:
                            date: '$orderDate'
                    sortBy:
                        orderDate: 1
                    output:
                        cumulativeQuantityForYear:
                            $sum: '$quantity'
                            window:
                                documents: ['unbounded', 'current']
    -
        name: 'Use Documents Window to Obtain Moving Average Quantity for Each Year'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/setWindowFields/#use-documents-window-to-obtain-moving-average-quantity-for-each-year'
        pipeline:
            -
                $setWindowFields:
                    partitionBy:
                        # $year: '$orderDate'
                        $year:
                            date: '$orderDate'
                    sortBy:
                        orderDate: 1
                    output:
                        averageQuantity:
                            $avg: '$quantity'
                            window:
                                documents: [-1, 0]
    -
        name: 'Use Documents Window to Obtain Cumulative and Maximum Quantity for Each Year'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/setWindowFields/#use-documents-window-to-obtain-cumulative-and-maximum-quantity-for-each-year'
        pipeline:
            -
                $setWindowFields:
                    partitionBy:
                        # $year: '$orderDate'
                        $year:
                            date: '$orderDate'
                    sortBy:
                        orderDate: 1
                    output:
                        cumulativeQuantityForYear:
                            $sum: '$quantity'
                            window:
                                documents: ['unbounded', 'current']
                        maximumQuantityForYear:
                            $max: '$quantity'
                            window:
                                documents: ['unbounded', 'unbounded']
    -
        name: 'Range Window Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/setWindowFields/#range-window-example'
        pipeline:
            -
                $setWindowFields:
                    partitionBy: '$state'
                    sortBy:
                        price: 1
                    output:
                        quantityFromSimilarOrders:
                            $sum: '$quantity'
                            window:
                                range: [-10, 10]
    -
        name: 'Use a Time Range Window with a Positive Upper Bound'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/setWindowFields/#use-a-time-range-window-with-a-positive-upper-bound'
        pipeline:
            -
                $setWindowFields:
                    partitionBy: '$state'
                    sortBy:
                        orderDate: 1
                    output:
                        recentOrders:
                            $push: '$orderDate'
                            window:
                                range: ['unbounded', 10]
                                unit: 'month'
    -
        name: 'Use a Time Range Window with a Negative Upper Bound'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/setWindowFields/#use-a-time-range-window-with-a-negative-upper-bound'
        pipeline:
            -
                $setWindowFields:
                    partitionBy: '$state'
                    sortBy:
                        orderDate: 1
                    output:
                        recentOrders:
                            $push: '$orderDate'
                            window:
                                range: ['unbounded', -10]
                                unit: 'month'
