# $schema: ../schema.json
name: $sort
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/sort/'
type:
    - stage
encode: single
description: |
    Reorders the document stream by a specified sort key. Only the order changes; the documents remain unmodified. For each input document, outputs one document.
arguments:
    -
        name: sort
        type:
            - expression
            - sortSpec
        variadic: object
tests:
    -
        name: 'Ascending Descending Sort'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/sort/#ascending-descending-sort'
        pipeline:
            -
                $sort:
                    age: -1
                    posts: 1
    -
        name: 'Text Score Metadata Sort'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/sort/#text-score-metadata-sort'
        pipeline:
            -
                $match:
                    $text:
                        $search: 'operating'
            -
                $sort:
                    score:
                        $meta: 'textScore'
                    posts: -1
