# $schema: ../schema.json
name: $sortByCount
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/sortByCount/'
type:
    - stage
encode: single
description: |
    Groups incoming documents based on the value of a specified expression, then computes the count of documents in each distinct group.
arguments:
    -
        name: expression
        type:
            - expression
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/sortByCount/#example'
        pipeline:
            -
                # The builder uses the verbose form of the $unwind operator
                # $unwind: '$tags'
                $unwind:
                    path: '$tags'
            -
                $sortByCount: '$tags'
