# $schema: ../schema.json
name: $unset
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/unset/'
type:
    - stage
encode: single
description: |
    Removes or excludes fields from documents.
    Alias for $project stage that removes or excludes fields.
arguments:
    -
        name: field
        type:
            - fieldPath
        variadic: array
