# $schema: ../schema.json
name: $unwind
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/unwind/'
type:
    - stage
encode: object
description: |
    Deconstructs an array field from the input documents to output a document for each element. Each output document replaces the array with an element value. For each input document, outputs n documents where n is the number of array elements and can be zero for an empty array.
arguments:
    -
        name: path
        type:
            - arrayFieldPath
        description: |
            Field path to an array field.
    -
        name: includeArrayIndex
        type:
            - string
        optional: true
        description: |
            The name of a new field to hold the array index of the element. The name cannot start with a dollar sign $.
    -
        name: preserveNullAndEmptyArrays
        type:
            - bool
        optional: true
        description: |
            If true, if the path is null, missing, or an empty array, $unwind outputs the document.
            If false, if path is null, missing, or an empty array, $unwind does not output a document.
            The default value is false.
tests:
    -
        name: 'Unwind Array'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/unwind/#unwind-array'
        pipeline:
            -
                # Example uses the short form, the builder always generates the verbose form
                # $unwind: '$sizes'
                $unwind:
                    path: '$sizes'
    -
        name: 'preserveNullAndEmptyArrays'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/unwind/#preservenullandemptyarrays'
        pipeline:
            -
                $unwind:
                    path: '$sizes'
                    preserveNullAndEmptyArrays: true
    -
        name: 'includeArrayIndex'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/unwind/#includearrayindex'
        pipeline:
            -
                $unwind:
                    path: '$sizes'
                    includeArrayIndex: 'arrayIndex'
    -
        name: 'Group by Unwound Values'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/unwind/#group-by-unwound-values'
        pipeline:
            -
                $unwind:
                    path: '$sizes'
                    preserveNullAndEmptyArrays: true
            -
                $group:
                    _id: '$sizes'
                    averagePrice:
                        $avg: '$price'
            -
                $sort:
                    averagePrice: -1
    -
        name: 'Unwind Embedded Arrays'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/unwind/#unwind-embedded-arrays'
        pipeline:
            -
                # Example uses the short form, the builder always generates the verbose form
                # $unwind: '$items'
                $unwind:
                    path: '$items'
            -
                # Example uses the short form, the builder always generates the verbose form
                # $unwind: '$items.tags'
                $unwind:
                    path: '$items.tags'
            -
                $group:
                    _id: '$items.tags'
                    totalSalesAmount:
                        $sum:
                            $multiply:
                                - '$items.price'
                                - '$items.quantity'
