# $schema: ../schema.json
name: $bitsAnySet
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/bitsAnySet/'
type:
    - fieldQuery
encode: single
description: |
    Matches numeric or binary values in which any bit from a set of bit positions has a value of 1.
arguments:
    -
        name: bitmask
        type:
            - int
            - binData
            - array # of int
