# $schema: ../schema.json
name: $bitsAnyClear
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/bitsAnyClear/'
type:
    - fieldQuery
encode: single
description: |
    Matches numeric or binary values in which any bit from a set of bit positions has a value of 0.
arguments:
    -
        name: bitmask
        type:
            - int
            - binData
            - array # of int
tests:
    -
        name: 'Bit Position Array'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/query/bitsAnyClear/#bit-position-array'
        pipeline:
            -
                $match:
                    a:
                        $bitsAnyClear: [1, 5]
    -
        name: 'Integer Bitmask'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/query/bitsAnyClear/#integer-bitmask'
        pipeline:
            - $match:
                  a:
                      $bitsAnyClear: 35
    -
        name: 'BinData Bitmask'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/query/bitsAnyClear/#bindata-bitmask'
        pipeline:
            - $match:
                  a:
                      $bitsAnyClear: !bson_binary 'MA=='
