# $schema: ../schema.json
name: $center
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/center/'
type:
    - geometry
encode: single
description: |
    Specifies a circle using legacy coordinate pairs to $geoWithin queries when using planar geometry. The 2d index supports $center.
arguments:
    -
        name: value
        type:
            - array
