# $schema: ../schema.json
name: $comment
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/comment/'
type:
    - query
encode: single
description: |
    Adds a comment to a query predicate.
arguments:
    -
        name: comment
        type:
            - string
