# $schema: ../schema.json
name: $elemMatch
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/elemMatch/'
type:
    - fieldQuery
encode: object
description: |
    The $elemMatch operator matches documents that contain an array field with at least one element that matches all the specified query criteria.
arguments:
    -
        name: query
        type:
            - query
