# $schema: ../schema.json
name: $in
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/in/'
type:
    - fieldQuery
encode: single
description: |
    Matches any of the values specified in an array.
arguments:
    -
        name: value
        type:
            - array # of expression
