# $schema: ../schema.json
name: $natural
link: 'https://www.mongodb.com/docs/v7.0/reference/operator/meta/natural/'
type:
    - expression
encode: object
description: |
    A special hint that can be provided via the sort() or hint() methods that can be used to force either a forward or reverse collection scan.
