# $schema: ../schema.json
name: $near
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/near/'
type:
    - fieldQuery
encode: dollar_object
description: |
    Returns geospatial objects in proximity to a point. Requires a geospatial index. The 2dsphere and 2d indexes support $near.
arguments:
    -
        name: geometry
        type:
            - geometry
    -
        name: maxDistance
        type:
            - number
        optional: true
        description: |
            Distance in meters. Limits the results to those documents that are at most the specified distance from the center point.
    -
        name: minDistance
        type:
            - number
        optional: true
        description: |
            Distance in meters. Limits the results to those documents that are at least the specified distance from the center point.
tests:
    -
        name: 'Query on GeoJSON Data'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/query/near/#query-on-geojson-data'
        pipeline:
            -
                $match:
                    location:
                        $near:
                            $geometry:
                                type: 'Point'
                                coordinates:
                                    - -73.9667
                                    - 40.78
                            $minDistance: 1000
                            $maxDistance: 5000
