# $schema: ../schema.json
name: $nearSphere
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/nearSphere/'
type:
    - fieldQuery
encode: object
description: |
    Returns geospatial objects in proximity to a point on a sphere. Requires a geospatial index. The 2dsphere and 2d indexes support $nearSphere.
arguments:
    -
        name: geometry
        type:
            - geometry
    -
        name: maxDistance
        type:
            - number
        optional: true
        description: |
            Distance in meters.
    -
        name: minDistance
        type:
            - number
        optional: true
        description: |
            Distance in meters. Limits the results to those documents that are at least the specified distance from the center point.
tests:
    -
        name: 'Specify Center Point Using GeoJSON'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/query/nearSphere/#specify-center-point-using-geojson'
        pipeline:
            -
                $match:
                    location:
                        $nearSphere:
                            $geometry:
                                type: 'Point'
                                coordinates:
                                    - -73.9667
                                    - 40.78
                            $minDistance: 1000
                            $maxDistance: 5000
    -
        name: 'Specify Center Point Using Legacy Coordinates'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/query/nearSphere/#specify-center-point-using-legacy-coordinates'
        pipeline:
            -
                $match:
                    location:
                        $nearSphere:
                            - -73.9667
                            - 40.78
                        $maxDistance: 0.1
