# $schema: ../schema.json
name: $where
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/where/'
type:
    - query
encode: single
description: |
    Matches documents that satisfy a JavaScript expression.
arguments:
    -
        name: function
        type:
            - javascript
