name: "Tests"

on:
  pull_request:
    branches:
      - "[0-9]+.[0-9]+"
      - "feature/*"
    paths-ignore:
      - "docs/**"
  push:
    branches:
      - "[0-9]+.[0-9]+"
      - "feature/*"
    paths-ignore:
      - "docs/**"

jobs:
  phpunit:
    name: "PHPUnit tests"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: true
      matrix:
        os:
          - "ubuntu-20.04"
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
        mongodb-version:
          - "4.4"
        driver-version:
          - "mongodb/mongo-php-driver@master"
        topology:
          - "server"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2

      - id: setup-mongodb
        uses: mongodb-labs/drivers-evergreen-tools@master
        with:
          version: ${{ matrix.mongodb-version }}
          topology: ${{ matrix.topology }}

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: "mongodb-${{ matrix.driver-version }}"
          key: "extcache-v1"

      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: "pecl"
          extensions: "mongodb-${{ matrix.driver-version }}"
          coverage: "none"
          ini-values: "zend.assertions=1"

      - name: "Show driver information"
        run: "php --ri mongodb"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@2.2.0"
        with:
          composer-options: "--no-suggest"

      - name: "Run PHPUnit"
        run: "vendor/bin/simple-phpunit -v"
        env:
          SYMFONY_DEPRECATIONS_HELPER: 999999
          MONGODB_URI: ${{ steps.setup-mongodb.outputs.cluster-uri }}
